disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
    - for_where
    - multiple_closures_with_trailing_closure
    - object_literal
    - attributes
    - file_header

opt_in_rules: # some rules are only opt-in
        - attributes
        - closure_spacing
        - fatal_error_message
        - first_where
        - nimble_operator
        - object_literal
        - operator_usage_whitespace
        - private_outlet
        - redundant_nil_coalescing
        - switch_case_on_newline

excluded: # paths to ignore during linting. Takes precedence over `included`.


# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 140
function_body_length:
  - 100
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  allowed_symbols: "_"
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
