language: swift
os: osx
osx_image: xcode10.2
before_script:
- gem install xcpretty
script:
- set -o pipefail && xcodebuild -scheme App -destination "platform=iOS Simulator,name=iPhone 8,OS=12.0" -enableCodeCoverage YES clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
after_success:
- bash <(curl -s https://codecov.io/bash)
